---
name: AmbiHue
version: "1.1.0"
slug: ambihue
description: "ambihue = Ambilight and Hue connected again!"
url: https://github.com/klimak000/ambihue
arch:
  - aarch64
  - amd64
  - armv7
ports:
  "1926/tcp": 1926
  "8080/tcp": 8080
options:
  # userconfig.example.yaml is a template for userconfig.yaml
  user_config_yaml: "copy userconfig.example.yaml"
schema:
  user_config_yaml: "str"
init: false
boot: manual
environment: USER_CONFIG_YAML
