---
name: AmbiHue
version: "1.0"
slug: ambihue
description: "ambihue = Ambilight and Hue connected again!"
url: https://github.com/klimak000/...
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  "1926/tcp": 1926
  "8080/tcp": 8080
options:
  # TODO remove?
  my_config_field: "5"
schema:
  my_config_field: "int"
init: false
