---
ambilight_tv:
  # SEE README.md for more details
  protocol: "https://" # "http://" or "https://"
  ip: replace_me # IP address of the TV
  port: "1926" # 1925 for APIv5, 1926->APIv6? or 1925->HTTP, 1926->HTTPS?
  api_version: "6" # API version of the TV: 1, 5 or 6
  path: "ambilight/processed" # leave default. see code in `ambilight_tv.py`
  wait_for_startup_s: 29 # Timeout for pinging device before reporting an error
  power_on_time_s: 8 # Timeout to FINISH TV booting before sending commands

hue_entertainment_group:
  # SEE README.md for more details
  _identification: "replace_me"
  _rid: "replace_me"
  _ip_address: "replace_me"
  _swversion: 1972004020
  _username: "replace_me"
  _hue_app_id: "replace_me"
  _client_key: "replace_me"
  _name: "Hue Bridge"
  index: 0 # Your Entertainment Area selection by index - manual adjustment

lights_setup:
  # SEE README.md for more details
  A_name: "sofa_behind"
  A_id: 0
  A_positions: [0, 1]
  B_name: "go_up"
  B_id: 1
  B_positions: [2, 3]
  # lights can be disabled:
  # C_name: "right"
  # C_id: 2
  # C_positions: [3, 4]
  # D_name: "left"
  # D_id: 3
  # D_positions: [12, 13]
