---
name: Build Docker Image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --target linters .
