---
name: Run SuperLinter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # super linter requires git history to work properly

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_PYINK: false # prefer Black
          VALIDATE_CHECKOV: false # prefer Hadolint
          VALIDATE_MARKDOWN_PRETTIER: false # prefer Markdownlint
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
